# Generated by Django 5.0.1 on 2024-02-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
